### ISSUE TITLE
Yabai not found

### ISSUE THREAD

**Issue by stefan-ernst** [grad-dev/yabai-spaces-widget#1]
Thanks for providing this widget!

After installation, the widget says "Yabai not found", even though when executing: 

"yabai -m query --spaces" in the terminal, a json with 10 spaces is returned.

(yabai is located in homebrew bin folder, which is in the PATH)

**Comment by stefan-ernst** [comment]
I killed the process and suddenly it worked.

**Comment by graddotdev** [comment]
I'm glad the issue has been resolved. May I ask how you found out about this repository?

**Comment by stefan-ernst** [comment]
i was looking for a mac space widget via google and this page came as the 2nd result: https://iosexample.com/yabai-spaces-widget-a-macos-app-that-adds-a-widget-to-your-status-bar/

**Comment by graddotdev** [comment]
Interesting. Thank you 😊
